definitions:
  dto.CreateAccountRequestDto:
    properties:
      active:
        type: boolean
      dateOfBirth:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  dto.GetAccountResponseDto:
    properties:
      active:
        type: boolean
      email:
        type: string
      id:
        type: string
      person:
        $ref: '#/definitions/dto.PersonResponseDto'
    type: object
  dto.PersonResponseDto:
    properties:
      dateOfBirth:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      phone:
        type: string
    type: object
  errors.Err:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  errors.HTTPError:
    properties:
      error:
        $ref: '#/definitions/errors.Err'
    type: object
info:
  contact: {}
paths:
  /api/v1/account:
    post:
      consumes:
      - application/json
      description: Creates a new account
      parameters:
      - description: Account data
        in: body
        name: CreateAccountRequestDto
        required: true
        schema:
          $ref: '#/definitions/dto.CreateAccountRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.GetAccountResponseDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: Create a new account
      tags:
      - account
  /api/v1/account/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an existing account record
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetAccountResponseDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: Delete an account
      tags:
      - account
    get:
      consumes:
      - application/json
      description: Get account record by account ID.
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetAccountResponseDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: Get account by ID
      tags:
      - account
swagger: "2.0"
