repos:
  - repo: https://github.com/ssengalanto/go-pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: go-fmt
      # id: go-vet
      - id: go-test
      - id: go-mod-tidy
      - id: golangci-lint