repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
  - repo: https://github.com/ssengalanto/revidere
    rev: v1.0.0
    hooks:
      - id: go-fmt
      # id: go-vet
      - id: go-test
      - id: go-mod-tidy
      - id: golangci-lint
