version: '3.9'

services:
  postgres:
    container_name: pgsql
    image: postgres:15.0-alpine
    ports:
      - ${PGSQL_PORT}:${PGSQL_PORT}
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DB: ${PGSQL_DB}
    volumes:
      - ./volumes/pgsql/:/var/lib/postgresql/data/

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./volumes/mongodb/:/var/lib/mongodb/data/

  redis:
    container_name: redis
    image: redislabs/rejson:latest
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  redisinsight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - ${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}

# TODO: update services to create connection to internal source.
#  account:
#    container_name: account-service
#    image: ${APP_NAME}-account
#    build:
#      context: .
#      target: development
#    restart: always
#    volumes:
#      - .:/app
#    ports:
#      - ${ACCOUNT_SERVICE_PORT}:${ACCOUNT_SERVICE_PORT}
#    deploy:
#      mode: replicated
#      replicas: 1
