version: '3.9'

services:
  postgres:
    container_name: pgsql
    image: postgres:15.0-alpine
    ports:
      - ${PGSQL_PORT}:${PGSQL_PORT}
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DB: ${PGSQL_DB}
    volumes:
      - ./volumes/pgsql/:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redislabs/rejson:latest
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  redisinsight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - ${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}

  account:
    container_name: account-service
    image: ${APP_NAME}-account
    build:
      context: .
      target: development
    restart: always
    volumes:
      - .:/app
    ports:
      - ${ACCOUNT_SERVICE_PORT}:${ACCOUNT_SERVICE_PORT}
    deploy:
      mode: replicated
      replicas: 1
