version: "3"

env:
  ENV: development

dotenv: [ '.env.{{ENV}}' ]

includes:
  app:
    taskfile: ./tasks/App.yaml
  docker:
    taskfile: ./tasks/Docker.yaml
  pg:
    taskfile: ./tasks/Pgsql.yaml

vars:
  PACKAGES:
    sh: go list ./...

tasks:
  default:
    desc: List all the available tasks.
    cmds:
      - task --list
    silent: true

  init:
    desc: Install required dependencies (macOS).
    cmds:
      - brew install go-task/tap/go-task
      - brew install golangci-lint
      - brew install golang-migrate
      - brew install pre-commit
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/golang/mock/mockgen@v1.6.0
      - pre-commit install

  swag:gen:
    desc: Generate swagger docs for services.
    summary: |
      Generate swagger docs for services.

      Arguments:
      BIN = service name

      Example:
      `task swag:gen BIN=<service-name>`
    cmds:
      - swag init -g ./cmd/{{.BIN}}/main.go -o ./cmd/{{.BIN}}/docs

  run:
    desc: Run the application.
    cmds:
      - task docker:compose-up

  run:account:
    desc: Run the account service.
    summary: |
      Run the account service in a docker container on port {{.ACCOUNT_SERVICE_PORT}}.
    cmds:
      - task docker:build BIN=account
      - task docker:run BIN=account PORT={{.ACCOUNT_SERVICE_PORT}}
