version: "3"

env:
  ENV: development

dotenv: [ '.env.{{.ENV}}' ]

includes:
  app:
    taskfile: ./tasks/App.yaml
  docker:
    taskfile: ./tasks/Docker.yaml
  pg:
    taskfile: ./tasks/Pgsql.yaml
  mock:
    taskfile: ./tasks/Mock.yaml

vars:
  PACKAGES:
    sh: go list ./...
  PGSQL_DSN: postgres://{{.PGSQL_USER}}:{{.PGSQL_PASSWORD}}@localhost:{{.PGSQL_PORT}}/{{.PGSQL_DB_NAME}}?{{.PGSQL_QUERY_PARAMS}}

tasks:
  default:
    desc: List all the available tasks.
    cmds:
      - task --list
    silent: true

  init:
    desc: Install required dependencies (macOS).
    cmds:
      - brew install go-task/tap/go-task
      - brew install golangci-lint
      - brew install golang-migrate
      - brew install pre-commit
      - go install github.com/cosmtrek/air@latest
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/golang/mock/mockgen@v1.6.0
      - pre-commit install

  swag:gen:
    desc: Generate swagger docs for services.
    summary: |
      Generate swagger docs for services.

      Arguments:
      BIN = service name

      Example:
      `task swag:gen BIN=<service-name>`
    cmds:
      - swag init -g ./cmd/{{.BIN}}/main.go -o ./cmd/{{.BIN}}/docs

  build:images:
    desc: Build images for all services.
    cmds:
      - task docker:build BIN=account

  run:
    desc: Run the application in local environment.
    deps:
      - build:images
    cmds:
      - task docker:compose
