version: "3"

dotenv: [ '.env.development' ]

includes:
  app:
    taskfile: ./tasks/App.yaml
  docker:
    taskfile: ./tasks/Docker.yaml
  pg:
    taskfile: ./tasks/Postgres.yaml

vars:
  PACKAGES:
    sh: go list ./...

tasks:
  default:
    desc: List all the available tasks.
    cmds:
      - task --list
    silent: true

  init:
    desc: Install required dependencies (macOS).
    cmds:
      - brew install go-task/tap/go-task
      - brew install golangci-lint
      - brew install golang-migrate
      - brew install pre-commit
      - pre-commit install

  run:
    desc: Run the application.
    cmds:
      - task docker:compose-up

  run:account:
    desc: Run the account service.
    summary: |
      Run the account service in a docker container on port {{.ACCOUNT_SERVICE_PORT}}.
    cmds:
      - task docker:build BIN=account
      - task docker:run BIN=account PORT={{.ACCOUNT_SERVICE_PORT}}
