name: development

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_APP_NAME: ${{ secrets.APP_NAME }}
          envkey_APP_ENV: ${{ secrets.APP_ENV }}
          envkey_LOG_TYPE: ${{ secrets.LOG_TYPE }}
          envkey_CONFIG_TYPE: ${{ secrets.CONFIG_TYPE }}
          envkey_ACCOUNT_SERVICE_PORT: ${{ secrets.ACCOUNT_SERVICE_PORT }}
          envkey_PGSQL_USER: ${{ secrets.PGSQL_USER }}
          envkey_PGSQL_PASSWORD: ${{ secrets.PGSQL_PASSWORD }}
          envkey_PGSQL_DB: ${{ secrets.PGSQL_DB }}
          envkey_PGSQL_PORT: ${{ secrets.PGSQL_PORT }}
          envkey_PGSQL_DSN: ${{ secrets.PGSQL_DSN }}
          envkey_REDIS_PORT: ${{ secrets.REDIS_PORT }}
          envkey_REDIS_URL: ${{ secrets.REDIS_URL }}
          envkey_REDIS_DB: ${{ secrets.REDIS_DB }}
          envkey_REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          envkey_REDIS_INSIGHT_PORT: ${{ secrets.REDIS_INSIGHT_PORT }}
          envkey_REDIS_INSIGHT_URL: ${{ secrets.REDIS_INSIGHT_URL }}
          directory: ../..
          file_name: .env.development

      - name: build
        run: go build -v ./...

      - name: test
        run: go test -v -coverprofile=profile.cov ./...

      - name: send test coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
